name: CI/CD for mini app

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
        
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

